export const categorizeSkill = (skillName) => {
  const normalizedSkill = skillName.toLowerCase().trim();

  const categories = {
    "Programming & Software Development": [
      "javascript",
      "python",
      "java",
      "c++",
      "c#",
      "ruby",
      "php",
      "swift",
      "kotlin",
      "go",
      "rust",
      "typescript",
      "html",
      "css",
      "react",
      "angular",
      "vue",
      "node.js",
      "django",
      "flask",
      "spring",
      "dotnet",
      "laravel",
      "git",
      "docker",
      "kubernetes",
      "jenkins",
      "aws",
      "azure",
      "gcp",
      "sql",
      "nosql",
      "mongodb",
      "postgresql",
      "mysql",
      "redis",
      "graphql",
      "rest api",
      "soap",
      "agile",
      "scrum",
      "kanban",
      "jira",
      "selenium",
      "junit",
      "pytest",
      "mocha",
      "jest",
      "cypress",
    ],
    "Data & Analytics": [
      "sql",
      "python",
      "r",
      "excel",
      "tableau",
      "power bi",
      "google analytics",
      "sas",
      "spss",
      "matlab",
      "pandas",
      "numpy",
      "scikit-learn",
      "tensorflow",
      "pytorch",
      "keras",
      "hadoop",
      "spark",
      "hive",
      "kafka",
      "airflow",
      "snowflake",
      "bigquery",
      "redshift",
      "looker",
      "dax",
      "vba",
      "statistics",
      "probability",
      "linear algebra",
      "calculus",
      "machine learning",
      "deep learning",
      "nlp",
      "computer vision",
      "data mining",
      "data warehousing",
      "etl",
      "data visualization",
      "business intelligence",
    ],
    "AI & Machine Learning": [
      "machine learning",
      "deep learning",
      "neural networks",
      "nlp",
      "computer vision",
      "reinforcement learning",
      "generative ai",
      "llm",
      "transformers",
      "bert",
      "gpt",
      "stable diffusion",
      "midjourney",
      "dall-e",
      "tensorflow",
      "pytorch",
      "keras",
      "scikit-learn",
      "opencv",
      "hugging face",
      "langchain",
      "vector databases",
      "pinecone",
      "chroma",
      "weaviate",
    ],
    "Cloud & DevOps": [
      "aws",
      "azure",
      "gcp",
      "docker",
      "kubernetes",
      "jenkins",
      "gitlab ci",
      "github actions",
      "circleci",
      "travis ci",
      "terraform",
      "ansible",
      "chef",
      "puppet",
      "vagrant",
      "linux",
      "bash",
      "shell scripting",
      "powershell",
      "networking",
      "security",
      "monitoring",
      "logging",
      "prometheus",
      "grafana",
      "elk stack",
      "splunk",
      "datadog",
      "new relic",
      "pagerduty",
    ],
    Cybersecurity: [
      "network security",
      "application security",
      "cloud security",
      "information security",
      "penetration testing",
      "ethical hacking",
      "vulnerability assessment",
      "incident response",
      "forensics",
      "cryptography",
      "identity and access management",
      "iam",
      "sso",
      "mfa",
      "firewalls",
      "vpn",
      "ids/ips",
      "siem",
      "soc",
      "cissp",
      "ceh",
      "oscp",
      "comptia security+",
    ],
    "Design & Creative": [
      "graphic design",
      "ui design",
      "ux design",
      "web design",
      "product design",
      "logo design",
      "branding",
      "illustration",
      "animation",
      "motion graphics",
      "video editing",
      "photography",
      "photoshop",
      "illustrator",
      "indesign",
      "xd",
      "figma",
      "sketch",
      "invision",
      "after effects",
      "premiere pro",
      "final cut pro",
      "davinci resolve",
      "blender",
      "maya",
      "cinema 4d",
      "3ds max",
      "unity",
      "unreal engine",
    ],
    "Business & Management": [
      "project management",
      "product management",
      "program management",
      "operations management",
      "strategic planning",
      "business analysis",
      "business development",
      "sales",
      "marketing",
      "finance",
      "accounting",
      "human resources",
      "leadership",
      "team management",
      "communication",
      "negotiation",
      "problem solving",
      "decision making",
      "time management",
      "organization",
      "agile",
      "scrum",
      "kanban",
      "lean",
      "six sigma",
      "pmp",
      "prince2",
    ],
    "Marketing & Advertising": [
      "digital marketing",
      "social media marketing",
      "content marketing",
      "email marketing",
      "seo",
      "sem",
      "ppc",
      "google ads",
      "facebook ads",
      "instagram ads",
      "linkedin ads",
      "twitter ads",
      "tiktok ads",
      "copywriting",
      "content writing",
      "blogging",
      "storytelling",
      "brand management",
      "market research",
      "analytics",
      "google analytics",
      "hubspot",
      "salesforce",
      "mailchimp",
      "convertkit",
    ],
    "Sales & Customer Success": [
      "sales",
      "business development",
      "account management",
      "customer success",
      "customer support",
      "customer service",
      "lead generation",
      "prospecting",
      "cold calling",
      "email outreach",
      "negotiation",
      "closing",
      "crm",
      "salesforce",
      "hubspot",
      "zendesk",
      "intercom",
      "drift",
    ],
    "Finance & Accounting": [
      "accounting",
      "finance",
      "bookkeeping",
      "auditing",
      "taxation",
      "financial analysis",
      "financial modeling",
      "budgeting",
      "forecasting",
      "valuation",
      "investment banking",
      "private equity",
      "venture capital",
      "corporate finance",
      "personal finance",
      "excel",
      "quickbooks",
      "xero",
      "sap",
      "oracle",
      "netsuite",
    ],
    "Human Resources": [
      "recruitment",
      "talent acquisition",
      "onboarding",
      "employee relations",
      "performance management",
      "compensation and benefits",
      "payroll",
      "hris",
      "workday",
      "bamboo hr",
      "adp",
      "gusto",
      "culture",
      "diversity and inclusion",
      "learning and development",
      "training",
    ],
    "Interpersonal & Soft Skills": [
      "communication",
      "teamwork",
      "collaboration",
      "leadership",
      "problem solving",
      "critical thinking",
      "adaptability",
      "flexibility",
      "creativity",
      "innovation",
      "emotional intelligence",
      "empathy",
      "active listening",
      "conflict resolution",
      "negotiation",
      "persuasion",
      "public speaking",
      "presentation skills",
      "time management",
      "organization",
      "stress management",
    ],
    Languages: [
      "english",
      "spanish",
      "french",
      "german",
      "chinese",
      "mandarin",
      "japanese",
      "korean",
      "italian",
      "portuguese",
      "russian",
      "arabic",
      "hindi",
      "bengali",
      "punjabi",
      "urdu",
      "turkish",
      "dutch",
      "swedish",
      "norwegian",
      "danish",
      "finnish",
      "polish",
      "greek",
      "hebrew",
      "thai",
      "vietnamese",
      "indonesian",
      "malay",
    ],
  };

  for (const [category, skills] of Object.entries(categories)) {
    if (skills.includes(normalizedSkill)) {
      return category;
    }
  }

  // Fallback logic for partial matches or common keywords
  if (
    normalizedSkill.includes("developer") ||
    normalizedSkill.includes("programmer") ||
    normalizedSkill.includes("engineer")
  ) {
    return "Programming & Software Development";
  }
  if (
    normalizedSkill.includes("manager") ||
    normalizedSkill.includes("management")
  ) {
    return "Business & Management";
  }
  if (normalizedSkill.includes("designer")) {
    return "Design & Creative";
  }
  if (
    normalizedSkill.includes("analyst") ||
    normalizedSkill.includes("analytics")
  ) {
    return "Data & Analytics";
  }
  if (normalizedSkill.includes("consultant")) {
    return "Business & Management";
  }

  return "Others";
};
